global using LuneLib.Utilities;
global using LuneWoL.Common.LWoLPlayers;
global using LuneWoL.Content.Buffs.DOT;
global using LuneWoL.Core.Config;
global using LuneWoL.LWoL_IL_Edits;
global using LuneWoL.PressureCheckFolder.Mode2;
global using Microsoft.Xna.Framework;
global using Mono.Cecil.Cil;
global using MonoMod.Cil;
global using System;
global using System.ComponentModel;
global using System.IO;
global using System.Reflection;
global using System.Threading.Tasks;
global using Terraria;
global using Terraria.Audio;
global using Terraria.DataStructures;
global using Terraria.GameContent.Events;
global using Terraria.ID;
global using Terraria.ModLoader;
global using Terraria.ModLoader.Config;
global using Terraria.ModLoader.IO;
global using static LuneLib.Common.Players.LuneLibPlayer.LibPlayer;
global using static LuneLib.Utilities.Hashsets.HashSets;
global using static LuneLib.Utilities.LuneLibUtils;
global using static LuneLibAssets.Common.SoundClass;
global using static LuneWoL.LuneWoL;
global using static LuneWoL.PressureCheckFolder.LWoLDepthUtils;
